SistemaInscripcionCursos/Controllers/EstudiantesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SistemaInscripcionCursos.Models.ModeloCursos;
using SistemaInscripcionCursos.Models;

namespace SistemaInscripcionCursos.Controllers
{
    public class EstudiantesController : Controller
    {
        private ContextoDB db = new ContextoDB();

        // GET: Estudiantes
        public ActionResult Index()
        {
            var estudiantes = db.Estudiantes.Include(e => e.Carrera).Include(e => e.Universidad);
            return View(estudiantes.ToList());
        }

        // GET: Estudiantes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estudiante estudiante = db.Estudiantes.Find(id);
            if (estudiante == null)
            {
                return HttpNotFound();
            }
            return View(estudiante);
        }

        // GET: Estudiantes/Create
        public ActionResult Create()
        {

            var lista = db.Carreras.ToList();
            lista.Add(new Carrera {Id =  0, Nombre ="[Seleccione una carrera]"});
            

            ViewBag.CarreraId = new SelectList(lista.OrderBy(c => c.Nombre), "Id", "Nombre");
            ViewBag.UniversidadID = new SelectList(db.Universidades.OrderBy(u => u.Nombre), "Id", "Nombre");
            return View();
        }

        // POST: Estudiantes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nombre,Apellido,UniversidadID,CarreraId,Email,Telefono,Celular")] Estudiante estudiante)
        {
            if (ModelState.IsValid)
            {
                db.Estudiantes.Add(estudiante);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CarreraId = new SelectList(db.Carreras, "Id", "Nombre", estudiante.CarreraId);
            ViewBag.UniversidadID = new SelectList(db.Universidades, "Id", "Nombre", estudiante.UniversidadID);
            return View(estudiante);
        }

        // GET: Estudiantes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estudiante estudiante = db.Estudiantes.Find(id);
            if (estudiante == null)
            {
                return HttpNotFound();
            }
            ViewBag.CarreraId = new SelectList(db.Carreras, "Id", "Nombre", estudiante.CarreraId);
            ViewBag.UniversidadID = new SelectList(db.Universidades, "Id", "Nombre", estudiante.UniversidadID);
            return View(estudiante);
        }

        // POST: Estudiantes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nombre,Apellido,UniversidadID,CarreraId,Email,Telefono,Celular")] Estudiante estudiante)
        {
            if (ModelState.IsValid)
            {
                db.Entry(estudiante).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CarreraId = new SelectList(db.Carreras, "Id", "Nombre", estudiante.CarreraId);
            ViewBag.UniversidadID = new SelectList(db.Universidades, "Id", "Nombre", estudiante.UniversidadID);
            return View(estudiante);
        }

        // GET: Estudiantes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estudiante estudiante = db.Estudiantes.Find(id);
            if (estudiante == null)
            {
                return HttpNotFound();
            }
            return View(estudiante);
        }

        // POST: Estudiantes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Estudiante estudiante = db.Estudiantes.Find(id);
            db.Estudiantes.Remove(estudiante);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult InscribirCurso()
        {
            return View();
        }
    }
}

SistemaInscripcionCursos/Controllers/ProfesorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SistemaInscripcionCursos.Models;
using SistemaInscripcionCursos.Models.ModeloCursos;

namespace SistemaInscripcionCursos.Controllers
{
    public class ProfesorsController : Controller
    {
        private ContextoDB db = new ContextoDB();

        // GET: Profesors
        public ActionResult Index()
        {
            var profesores = db.Profesores.Include(p => p.Carrera).Include(p => p.Universidad);
            return View(profesores.ToList());
        }

        // GET: Profesors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profesor profesor = db.Profesores.Find(id);
            if (profesor == null)
            {
                return HttpNotFound();
            }
            return View(profesor);
        }

        // GET: Profesors/Create
        public ActionResult Create()
        {
            ViewBag.CarreraId = new SelectList(db.Carreras, "Id", "Nombre");
            ViewBag.UniversidadID = new SelectList(db.Universidades, "Id", "Nombre");
            return View();
        }

        // POST: Profesors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nombre,Apellido,UniversidadID,CarreraId,Email,Telefono,Celular")] Profesor profesor)
        {
            if (ModelState.IsValid)
            {
                db.Profesores.Add(profesor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CarreraId = new SelectList(db.Carreras, "Id", "Nombre", profesor.CarreraId);
            ViewBag.UniversidadID = new SelectList(db.Universidades, "Id", "Nombre", profesor.UniversidadID);
            return View(profesor);
        }

        // GET: Profesors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profesor profesor = db.Profesores.Find(id);
            if (profesor == null)
            {
                return HttpNotFound();
            }
            ViewBag.CarreraId = new SelectList(db.Carreras, "Id", "Nombre", profesor.CarreraId);
            ViewBag.UniversidadID = new SelectList(db.Universidades, "Id", "Nombre", profesor.UniversidadID);
            return View(profesor);
        }

        // POST: Profesors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nombre,Apellido,UniversidadID,CarreraId,Email,Telefono,Celular")] Profesor profesor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(profesor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CarreraId = new SelectList(db.Carreras, "Id", "Nombre", profesor.CarreraId);
            ViewBag.UniversidadID = new SelectList(db.Universidades, "Id", "Nombre", profesor.UniversidadID);
            return View(profesor);
        }

        // GET: Profesors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profesor profesor = db.Profesores.Find(id);
            if (profesor == null)
            {
                return HttpNotFound();
            }
            return View(profesor);
        }

        // POST: Profesors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Profesor profesor = db.Profesores.Find(id);
            db.Profesores.Remove(profesor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SistemaInscripcionCursos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                           @Html.ActionLink("Home", "Index", "Home")
                    </li>

                    
                    
                    <li class="dropdown">
                        <a class="dropdown-toggle"
                           data-toggle="dropdown" href="Estudiantes/index">
                            Estudiantes
                            <b class="caret"></b>
                        </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Listado", "Index", "Estudiantes")</li>
                        <li>@Html.ActionLink("Listado", "Index", "Estudiantes")</li>

                    </ul>
                    
                    
                    </li>
                    <li>@Html.ActionLink("Profesores", "Index", "Profesors")</li>

                    <li>@Html.ActionLink("Carreras", "Index", "Carreras")</li>
                    <li>@Html.ActionLink("Universidades", "Index", "universidads")</li>
                    <li class="dropdown">
                        <a class="dropdown-toggle"
                           data-toggle="dropdown" href="Estudiantes/index">
                            Cursos
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Ver Cursos", "Index", "Cursos")</li>
                            <li>@Html.ActionLink("Inscribir Cursos", "InscribirCurso", "Estudiantes")</li>

                        </ul>


                    </li>
                   
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>